homeassistant:

automation:
- alias: Daily snapshot at 3 AM
  initial_state: 'on'
  trigger:
    platform: time
    at: '3:00:00'
  action:
  - service: hassio.snapshot_full
    data_template:
      name: Automated Backup {{ now().strftime('%Y-%m-%d') }}

- alias: Upload dropbox 4AM
  initial_state: 'on'
  trigger:
    platform: time
    at: '4:00:00'
  action:
  - service: hassio.addon_stdin
    data:
      addon: "7be23ff5_dropbox_sync"
      input: {"command":"upload"}