homeassistant:
  customize:
    switch.projector:
      friendly_name: Projektor
      icon: mdi:projector

switch:
  - platform: broadlink
    host: 192.168.1.76
    mac: '34:ea:34:40:7c:69'
    switches:
      projector:
        friendly_name: Projektor
        command_on:
          'JgD4AQABKZMTEhITEhITEhMSExITEhMSExISExITEhITNxM3EhMSEhM3EzcSNxM3ExITEhI3ExITEhMSExITEhM2EzcTEhM3EgAF'
        command_off:
          'JgAgAQABKJMTEhUQFRATEhQRFBESExITEhITEhMSExITNxI3FRAVEBMSFDYUNRU1FBEUERI3ExIVNRMSFBESExQ1EzcTEhQ1EwAF'