homeassistant:
  customize:
    switch.reciver:
      friendly_name: Förstärkare
      icon: mdi:speaker
      emulated_hue: true


switch:
  - platform: broadlink
    host: 192.168.1.76
    mac: '34:ea:34:40:7c:69'
    switches:
      reciver:
        friendly_name: Förstärkare
        command_on:
          'JgBwAAABKZQUERQ3ExITNxM3FDcTNxMSEzcUERQ2FBEUERQRFBETNxQ3ExITNxM3FDcTEhMRFBEWDxQ3FRATERQRFDcTNxM3FAAFIgABKkkUAAxhAAEpSRQADGEAASlJFAAMYQABKUoVAAxfAAEpShMADQUAAAAAAAAAAA=='
        command_off:
          'JgCQAAABKZQVEBM3FBEVNRQ3EzcUNhQRFjUTEhU1ExITEhUQExIVNRUQFTUVNRY1EzcVEBQRExITNxQRFBEVEBMSFTUUNxM3EwAFIwABK0gTAAxhAAEpShUADF8AASlKFQAMYAABKUkVAAxgAAEpSRYADF8AASlKEwAMYQABKUoTAAxhAAErSBMADGIAASpIFAANBQAAAAAAAAAA'

      reciver_volume:
        friendly_name: Reciver Volume
        command_on:
          'JgBQAAABKZQTEhM3ExITNxQ3EzcTNxQRFDcTERQ3ExITEhMSExEUNxMSEzcUERM3FDcTEhMSExEUNxMSEzcTEhMSEzcUNxM3EwAFIwABKUoTAA0FAAAAAAAAAAA='
        command_off:
          'JgBQAAABKZQUERQ3ExEUNxM3FDYUNxMSEzcUERM3FBEUERQRFBETNxQ3EzcTEhM3FDcTEhMRFBEUERQRFDcTERQRFDcTNxQ2FAAFIwABKUkUAA0FAAAAAAAAAAA='

      reciver_mute:
        friendly_name: Reciver Mute
        command_on:
          'JgBYAAABKZQTEhM3FBETNxQ3EzcUNhQRFDcTEhM3ExITEhMSExITNxMSExITNxQ2FDcTEhMSExEUNxM3FBEUERMSEzcUNxM3EwAFIwABKUoTAAxhAAEqSRQADQU='

input_boolean:
  reciver_mute:
    name: Mute

input_number:
  volume_control:
    name: Volume
    min: -50
    max: -20
    step: 1

#  volume_control_previous:
#    name: Volume
#    min: -50
#    max: -30
#    step: 1

#sensor:
#  - platform: template
#    sensors:
#      volume_template:
#        friendly_name: Bullshit
#        value_template: "{{ states.input_number.volume_control.state|float - states.input_number.volume_control_previous.state|float }}"

#automation: 
#  - alias: Reset previous state slider
#    initial_state: on
#    trigger:
#      platform: state
#      entity_id: sensor.volume_template
#    action:
#     - service: input_number.set_value
#       data_template:
#         entity_id: input_number.volume_control_previous
#         value: "{{ states('input_number.volume_control') | int }}"

