homeassistant:

binary_sensor:
  - platform: template
    sensors:
      dish_washer_running:
        delay_on:
          minutes: 1
        delay_off:
          minutes: 5
        value_template: "{{ states('sensor.shelly_shplg_s_267f92_current_consumption')|float > 0 }}"

sensor:
  - platform: integration
    source: sensor.shelly_shplg_s_267f92_current_consumption
    name: dish_washer_energy_kwh
    unit_prefix: k
    round: 2

utility_meter:
  dish_washer_energy_monthly:
    source: sensor.dish_washer_energy_kwh
    cycle: monthly