homeassistant:
  customize:
    sensor.ender_3_job_percentage:
      friendly_name: Progress

octoprint:
  host: 192.168.1.86
  api_key: !secret octoprint_api_key
  name: Ender 3
  bed: true
  number_of_tools: 1
  sensors:
    monitored_conditions:
      - 'Current State'
      - 'Temperatures'
      - 'Job Percentage'
      - 'Time Elapsed'
      - 'Time Remaining'
  binary_sensors:
    monitored_conditions:
      - 'Printing'
      - 'Printing Error'

camera:
  - platform: mjpeg
    name: OctoPrint
    still_image_url: http://192.168.1.86/webcam/?action=snapshot
    mjpeg_url: http://192.168.1.86/webcam/?action=stream

binary_sensor:
  - platform: template
    sensors:
      octoprint_100_pct:
        friendly_name: "Octoprint 100%"
        value_template: "{{ states.sensor.ender_3_job_percentage.state < '99.9' }}"


script:
  3d_print_done:
    sequence: 
      - service: camera.snapshot
        data:
          entity_id: camera.octoprint
          filename: '/config/www/printer_image/3d_printer.jpg'
      - service: notify.home_assistant
        data:
          title: 3D-print
          message: 3D-print klar
          data:
            file: /config/www/printer_image/3d_printer.jpg

  3d_print_status:
    sequence: 
      - service: camera.snapshot
        data:
          entity_id: camera.octoprint
          filename: '/config/www/printer_image/3d_printer.jpg'
      - service: notify.home_assistant
        data:
          title: 3D-print
          message: Tid kvar, {{ states('sensor.ender_3_time_remaining') | int | timestamp_custom('%H:%M:%S', 0) }}
          data:
            file: /config/www/printer_image/3d_printer.jpg
          
sensor:
  - platform: template
    sensors:
      ender_3_time_remaining_template:
        friendly_name: "Octoprint time elapsed"
        value_template: "{{ states('sensor.ender_3_time_remaining') | int | timestamp_custom('%H:%M:%S', 0) }}"

