homeassistant:

input_select:
  produkt:
    name: Produkt
    options:
      - NA
      - Toalettpapper (st) #ID 7
      - Juice (l) #ID 5
      - Disktabletter (st) #ID 4

input_number:
  consume_drink_amount:
    name: Förbruka
    initial: 0
    min: 0
    max: 10

sensor:
  - platform: template
    sensors:
      input_select_product_id:
        value_template: >-
          {% if is_state('input_select.produkt', 'NA') %}
            NA
          {% elif is_state('input_select.produkt', 'Disktabletter (st)') %}
            4
          {% elif is_state('input_select.produkt', 'Juice (l)') %}
            5
          {% elif is_state('input_select.produkt', 'Toalettpapper (st)') %}
            7
          {% endif %}

input_boolean:
  consume_button:
    initial: off

input_text:
  avalible_amount:
    initial: " "
