homeassistant:

group:
  livingroom_lights:
    name: Vardagsrum
    entities:
      - light.livingroom_ceiling
      - light.livingroom_shelf
      - light.livingroom_window
      - light.monitor
      - light.kitchen_spotlights
      - light.led_strip
  
  hallway_lights:
    name: Hallen
    entities:
      - light.hallway_ceiling
      - light.hallway_table

  bedroom_lights:
    name: Sovrum
    entities:
      - light.bedroom_ceiling
      - light.bedroom_window
      - light.bed_table_lamp_left
      - light.bed_table_light_right
  
  bathroom_lights:
    name: Toalett
    entities:
     - light.bathroom_ceiling_2
     - light.bathroom_ceiling_3

  
  home_theater:
    name: Hemmabio
    entities:
      - input_boolean.home_theater_chromecast
      - switch.projector
      - switch.reciver
      - input_number.volume_control

  fridge_freezer:
    name: Vitvaror
    entities:
      - binary_sensor.door_sensor_freezer
      - binary_sensor.door_sensor_fridge
  
  phone_chargers:
    name: Mobilladdare
    entities: 
      - switch.phone_charger_jennifer
      - switch.phone_charger_rickard


  
