homeassistant:

script:
  turn_off_all_sleep: #Not the printer plug
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - switch.livingroom_monitor
            - switch.livingroom_shelf
            - switch.livingroom_window
            - switch.projector
            - switch.reciver
            - light.bathroom_ceiling_2
            - light.bathroom_ceiling_3
            - light.bedroom_ceiling
            - light.hallway_table
            - light.hallway_ceiling
            - light.kitchen_spotlights
            - light.kitchen_spotlight_1
            - light.kitchen_spotlight_2
            - light.kitchen_spotlight_3
            - light.led_strip
            - light.bed_table_light_right
            - light.bed_table_lamp_left
            - light.bedroom_window
            - switch.printer_light
            - switch.monitor
            - light.livingroom_ceiling