homeassistant: 
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 38
  unit_system: metric
  time_zone: Europe/Stockholm
  packages: !include_dir_named packages
  auth_providers:
    - type: legacy_api_password
      api_password: !secret api_password

# Configure a default setup of Home Assistant (automation, cloud, config, frontend, history, logbook, map, mobile app, )
default_config:

# Only store 3 days of history
recorder:
  purge_keep_days: 7

# Include location of themes
frontend:
  themes: !include_dir_merge_named themes/

# DuckDNS and SSL
http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem


# Pushbullet notification
notify:
  - name: Home_Assistant
    platform: pushbullet
    api_key: !secret api_key

# MQTT broker configuration
mqtt:
  broker: !secret broker
  port: !secret mqtt_port
  keepalive: 60
  client_id: homeassistant_master
  username: !secret mqtt_username
  password: !secret mqtt_password

# Shopping list
shopping_list:

# Lovelace yaml mode instead of configurator in GUI
lovelace:
  mode: yaml

lovelace_gen:

#Home assistant community
hacs:
  token: !secret hacs_token

ios:

tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    base_url: !secret base_url_tts 
    service_name: google_say

browser_mod:
