title: Home      
        
resources:                             
  - type: module
    url: /local/dwains-theme/plugins/cover-card.js?v=1
  - url: /community_plugin/custom-header/custom-header.js
    type: module
  - url: /community_plugin/decluttering-card/decluttering-card.js
    type: module
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/lovelace-card-mod/card-mod.js
    type: module
  - url: /community_plugin/light-entity-card/light-entity-card.js
    type: js
  - url: /community_plugin/mini-graph-card/mini-graph-card.js
    type: module
  - url: /community_plugin/lovelace-auto-entities/auto-entities.js
    type: module
  - url: /community_plugin/lovelace-layout-card/layout-card.js
    type: module
  - url: /community_plugin/custom-header/custom-header.js
    type: module
  - url: /local/community/tracker-card/tracker-card.js?track=true
    type: module
  - url: /local/community/vertical-stack-in-card/vertical-stack-in-card.js?track=true
    type: js
  - url: /local/community/slider-entity-row/slider-entity-row.js?track=true
    type: js
  - url: /local/community/bar-card/bar-card.js?track=true
    type: js
  - url: /local/community/fold-entity-row/fold-entity-row.js?track=true
    type: js
  - url: /local/community/popup-card/popup-card.js?track=true
    type: js
  - url: /local/community/card-tools/card-tools.js?track=true
    type: js
  - url: /community_plugin/lovelace-grocy-chores-card/grocy-chores-card.js?v=1.1
    type: js 
  - url: /local/community/toggle-lock-entity-row/toggle-lock-entity-row.js?v.1.0
    type: js 
  - url: /local/community/markdown-mod/markdown-mod.js?v1.0
    type: module
  - url: /community_plugin/weather-card/weather-card.js
    type: module
  - url: /community_plugin/calendar-card/calendar-card.js
    type: js
  - url: /community_plugin/atomic_calendar/atomic_calendar.js
    type: module

views:
  - !include /config/lovelace/100-mobile_view.yaml
  - !include /config/lovelace/110-all_lights_view.yaml
  - !include /config/lovelace/120-system_info_view.yaml
  - !include /config/lovelace/130-printer_view.yaml
  - !include /config/lovelace/140-vacuum_view.yaml
  - !include /config/lovelace/210-livingroom_room_view.yaml
  - !include /config/lovelace/220-bedroom_room_view.yaml
  - !include /config/lovelace/230-hallway_room_view.yaml
  - !include /config/lovelace/240-bathroom_room_view.yaml
  - !include /config/lovelace/250-home_information_view.yaml
  - !include /config/lovelace/310-livingroom_lights_view.yaml
  - !include /config/lovelace/320-bedroom_lights_view.yaml
  - !include /config/lovelace/330-home_theater_view.yaml
  - !include /config/lovelace/340-flower_view.yaml  
#  - !include /config/lovelace/070-floorplan-view.yaml
#  - !include /config/lovelace/010-mobile_view.yaml
#  - !include /config/lovelace/020-info_view.yaml
#  - !include /config/lovelace/030-control_view.yaml
#  - !include /config/lovelace/040-vacuum-3dprinter_view.yaml
#  - !include /config/lovelace/050-tools_view.yaml

decluttering_templates:
  !include_dir_merge_named lovelace/templates/decluttering-card-templates 


button_card_templates: 
  !include_dir_merge_named lovelace/templates/button-card-templates 

custom_header:
  hidden_tab_redirect: false 
  hide_tabs:
    - livingroom_room
    - bedroom_room
    - hallway_room  
    - bathroom_room
    - livingroom_lights
    - bedroom_lights
    - home_theater
    - home_information
    - flower_view
  compact_mode: true
  footer_mode: true