homeassistant:

light:
  - platform: switch
    name: livingroom shelf
    entity_id: switch.livingroom_shelf
  
  - platform: switch
    name: livingroom window
    entity_id: switch.livingroom_window

  - platform: switch
    name: monitor
    entity_id: switch.monitor