homeassistant:

light:
  - platform: mqtt
    name: livingroom ceiling
    command_topic: "cmnd/sonoff_8/power"
    state_topic: "stat/sonoff_8/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true