homeassistant:

google_assistant:
  project_id: !secret google_assistant_project_id
  service_account: !secret google_assistant_service_account
  exposed_domains:
    - light
    - input_boolean
    - cover

  entity_config:
    light.bedroom_window:
      name: Sovrums_fönster
      aliases: Sovrums fönster
    
    light.livingroom_window:
      name: Vardagsrums_fönster
      aliases:
        - Bollen    

    light.livingroom_shelf:
      name: Hyllan
      aliases:
        - Burken
        - Bokhyllan
    
    light.livingroom_ceiling:
      name: Vardagsrums_Taket
      aliases:
        - Kringlan
        - Mongolampan


    light.monitor:
      name: Monitor
      aliases:
        - Backlight
        - Skärm

    light.kitchen_spotlights:
      name: Spotlights
      aliases:
        - Spottarna
        - Spotlightsen
    
    light.led_strip:
      name: Led-strip
      aliases:
        - Bänken
        - Bänkbelysning
        - Diskbänken 

    input_boolean.home_theater:
      name: Hemmabio
      aliases:
        - Bion
        - Film
        - Hemmabion
        - Hembion

    switch.projector:
      name: Porjektor
      aliases:
        - Projen
        - Projektorn
        - Projektor

    switch.reciver:
      name: Förstärkare
      expose: true
      aliases:
        - Förstärkare
        - Förstärkaren
        - Reciver
        - Högtalare
        - Ljud
        - Ljudet
      
    cover.curtain_motor:
      name: Gardinen
      aliases:
        - Gardinen
        - Gardin
    
    switch.printer_light:
      name: Printer lampa
      expose: true
      aliases:
        - Printer lampan
        - Printer ljuset
        - 3d printer lampan
    
    switch.shelly_shplg_s_267fe1:
      name: Printer
      expose: true
      aliases: 
        - 3d printer
        - Buster


