homeassistant:

sensor:
  - platform: mqtt
    name: Bergpalm moisture
    state_topic: "homeassistant_slave/sensor/bergpalm_moisture/state"

  - platform: mqtt
    name: Blandning moisture
    state_topic: "homeassistant_slave/sensor/blandning_moisture/state"

  - platform: mqtt
    name: Citronfikus moisture
    state_topic: "homeassistant_slave/sensor/citronfikus_moisture/state"

  - platform: mqtt
    name: Guldpalm moisture
    state_topic: "homeassistant_slave/sensor/guldpalm_moisture/state"

  - platform: mqtt
    name: Pillerfikus moisture
    state_topic: "homeassistant_slave/sensor/pillerfikus_moisture/state"

  - platform: mqtt
    name: Sedum moisture
    state_topic: "homeassistant_slave/sensor/sedum_moisture/state"

  - platform: template
    sensors:
      flower_need_water_sensor:
        value_template: >-
          {{    
                  states('sensor.sedum_moisture')|float < 30
              or  states('sensor.bergpalm_moisture')|float < 30
              or  states('sensor.guldpalm_moisture')|float < 30
              or  states('sensor.citronfikus_moisture')|float < 30
              or  states('sensor.pillerfikus_moisture')|float < 30
          }} 